name: Build And Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  #To do, this can be pulled from the .csproj?
  JustFunctionalDockerImageVersion: "2.0.1"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2    
   
    - name: Test
      run: echo  ${{ env.GITHUB_REF_NAME}}
    
    
   
